# Generated by Django 2.1.15 on 2020-10-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercategory',
            old_name='code',
            new_name='usrcat_code',
        ),
        migrations.RenameField(
            model_name='usercategory',
            old_name='desc',
            new_name='usrcat_desc',
        ),
        migrations.RenameField(
            model_name='usercategory',
            old_name='remarks',
            new_name='usrcat_remarks',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='id',
        ),
        migrations.AddField(
            model_name='usercategory',
            name='usrcat_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='usercategory',
            name='usrcat_slno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='usercategory',
            table='UserCategory',
        ),
    ]
