# Generated by Django 2.1.15 on 2020-10-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201015_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercategory',
            old_name='usrcat_desc',
            new_name='usercat_desc',
        ),
        migrations.RenameField(
            model_name='usercategory',
            old_name='usrcat_remarks',
            new_name='usercat_remarks',
        ),
        migrations.RenameField(
            model_name='usercategory',
            old_name='usrcat_slno',
            new_name='usercat_slno',
        ),
    ]
