# Generated by Django 2.1.15 on 2020-09-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freighttypes',
            fields=[
                ('fretype_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('fretype_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('fretype_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('fretype_slno', models.IntegerField(blank=True, null=True, verbose_name='Serial no.')),
                ('fretype_remarks', models.CharField(blank=True, max_length=250, null=True, verbose_name='Remarks')),
                ('fretype_active', models.CharField(blank=True, max_length=1, null=True, verbose_name='Status')),
                ('fretype_nnc_code', models.CharField(blank=True, max_length=10, null=True)),
                ('fretype_whmcode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Freighttypes',
            },
        ),
        migrations.CreateModel(
            name='Vehiclecategory',
            fields=[
                ('vehcat_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('vehcat_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('vehcat_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('vehcat_wtcapacity', models.FloatField(blank=True, null=True, verbose_name='Weight capacity')),
                ('vehcat_length', models.FloatField(blank=True, null=True, verbose_name='Length')),
                ('vehcat_width', models.FloatField(blank=True, null=True, verbose_name='Width')),
                ('vehcat_ft', models.CharField(blank=True, max_length=50, null=True)),
                ('vehcat_kmrate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='KM Rate')),
                ('vehcat_slno', models.IntegerField(blank=True, null=True, verbose_name='Serial no.')),
                ('vehcat_active', models.CharField(blank=True, max_length=1, null=True)),
                ('vehcat_remarks', models.CharField(blank=True, max_length=250, null=True, verbose_name='Remarks')),
                ('vehcat_makerid', models.IntegerField(blank=True, null=True)),
                ('vehcat_maketime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VehicleCategory',
            },
        ),
        migrations.CreateModel(
            name='Vehiclemaster',
            fields=[
                ('vehmas_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('vehmas_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vehicle Number')),
                ('vehmas_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('vehmas_drivername', models.CharField(blank=True, max_length=20, null=True, verbose_name='Driver Name')),
                ('vehmas_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('vehmas_modepntr', models.IntegerField(blank=True, null=True)),
                ('vehmas_slno', models.IntegerField(blank=True, null=True)),
                ('vehmas_active', models.CharField(blank=True, max_length=1, null=True, verbose_name='Status')),
                ('vehmas_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('vehmas_makerid', models.IntegerField(blank=True, null=True)),
                ('vehmas_maketime', models.DateTimeField(blank=True, null=True)),
                ('vehmas_clntpntr', models.IntegerField(blank=True, null=True)),
                ('vehmas_catpntr', models.ForeignKey(db_column='vehcat_id', on_delete=django.db.models.deletion.CASCADE, to='app.Vehiclecategory', verbose_name='Category')),
                ('vehmas_frtyppntr', models.ForeignKey(blank=True, db_column='fretype_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Freighttypes', verbose_name='Vehicle Mode')),
            ],
            options={
                'db_table': 'VehicleMaster',
            },
        ),
    ]
