# Generated by Django 2.1.15 on 2020-09-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(choices=[('FL', 'Front Left'), ('FR', 'Front Right'), ('BL', 'Back Left'), ('BR', 'Back Right'), ('BL1', 'Back Left+1'), ('BR1', 'Back Right+1'), ('ST', 'Stepney'), ('OT', 'Others')], max_length=7, verbose_name='Description')),
                ('dtl', models.CharField(max_length=15, verbose_name='Tyre no.')),
                ('make', models.CharField(max_length=25, verbose_name='Make')),
                ('flt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vehiclemaster')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
