# Generated by Django 2.1.15 on 2020-12-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclecategory',
            options={'managed': False},
        ),
    ]
