# Generated by Django 2.1.15 on 2020-09-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tyre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaster',
            name='vehmas_id',
            field=models.IntegerField(db_column='vehmas_id', default=1, primary_key=True, serialize=False),
        ),
    ]
