# Generated by Django 2.1.15 on 2020-09-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200914_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freighttypes',
            name='fretype_id',
            field=models.IntegerField(db_column='fretype_id', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='vehcat_id',
            field=models.IntegerField(db_column='vehcat_id', default=1, primary_key=True, serialize=False),
        ),
    ]
