# Generated by Django 2.1.15 on 2020-12-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201201_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='lexpiry',
            field=models.DateField(blank=True, null=True, verbose_name='License expiry'),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='vehmas_frtyppntr',
            field=models.ForeignKey(blank=True, db_column='fretype_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Freighttypes', verbose_name='Vehicle Mode'),
        ),
    ]
