# Generated by Django 2.1.15 on 2020-12-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201201_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freighttypes',
            options={},
        ),
    ]
