# Generated by Django 2.1.15 on 2020-09-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200914_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freighttypes',
            name='fretype_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='vehcat_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehiclemaster',
            name='vehmas_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
