# Generated by Django 2.1.15 on 2020-09-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200914_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyre',
            name='flt',
        ),
        migrations.RemoveField(
            model_name='vehiclemaster',
            name='vehmas_catpntr',
        ),
        migrations.RemoveField(
            model_name='vehiclemaster',
            name='vehmas_frtyppntr',
        ),
        migrations.DeleteModel(
            name='Freighttypes',
        ),
        migrations.DeleteModel(
            name='Tyre',
        ),
        migrations.DeleteModel(
            name='Vehiclecategory',
        ),
        migrations.DeleteModel(
            name='Vehiclemaster',
        ),
    ]
