# Generated by Django 2.1.15 on 2020-12-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201201_1539'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='freighttypes',
            table='Freighttypes',
        ),
    ]
