# Generated by Django 2.1.15 on 2020-12-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201201_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaster',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Region'),
        ),
    ]
